### ISSUE TITLE
Panic when running job

### ISSUE THREAD

**Issue by alexef** [victorcoder/dkron#231] opened 2017-01-25 14:53 UTC
I observed that a cronjob is locked in "started" state since more than 10 minutes ago. When checking the log file on the node it was supposed to run, I saw that dkron panicked and restarted, but the job execution was left in "started". Since concurrency was set to _forbid_, no other job was started.

What could be the cause? There's nothing in the dkron server logs. This is the log from the agent on the node it was supposed to run:

> time="2017-01-25T15:27:35+01:00" level=info msg="agent: Starting job" job="cjms_fetch" node=watcher11 
> panic: invalid argument to Intn
> 
> goroutine 52938 [running]:
> panic(0x9c6e00, 0xc420291490)
> 	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
> math/rand.(*Rand).Intn(0xc42000e120, 0x0, 0x40402020201)
> 	/usr/local/opt/go/libexec/src/math/rand/rand.go:116 +0xd0
> math/rand.Intn(0x0, 0xe22be0)
> 	/usr/local/opt/go/libexec/src/math/rand/rand.go:247 +0x37
> github.com/victorcoder/dkron/dkron.(*AgentCommand).selectServer(0xc420133c70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/proc.go:72 +0x7c
> github.com/victorcoder/dkron/dkron.(*AgentCommand).queryRPCConfig(0xc420133c70, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/queries.go:149 +0xaa
> github.com/victorcoder/dkron/dkron.(*AgentCommand).invokeJob(0xc420133c70, 0xc42011f200, 0xc42007e680, 0x54d0c3, 0x180001)
> 	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/proc.go:61 +0x4d8
> github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop.func1(0xc420133c70, 0xc42011f200, 0xc42007e680)
> 	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:522 +0x43
> created by github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop
> 	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:525 +0x144c
>

**Comment by victorcoder** [comment] 2017-01-25 20:35
This is a great catch @alexef and one that needs to be fixed. 

The fact that no other jobs started if the concurrency is in *forbid* is the expected behaviour. The problem is that the job locked.

The error is in this line https://github.com/victorcoder/dkron/blob/master/dkron/proc.go#L72 that select a random server to return the response to the execution, it seems that the `listServers` method returned a wrong value. Probably an empty slice. That means that the node couldn't see any dkron servers at the time of responding with the execution result.

If your node is still up, could you check in dkron member list if the node is member of the cluster? `curl localhost:8080/v1/members`

**Comment by alexef** [comment] 2017-01-26 12:26
@victorcoder maybe I've checked too late, but the member list looked fine.

This happened again today and as a workaround I've changed the concurrency too allow :(

**Comment by alexef** [comment] 2017-03-16 16:46
What would be a fix for this issue? I really want to avoid job locking, this is quite a blocker for us.

**Comment by victorcoder** [comment] 2017-03-16 20:35
Let's prepare some extra logging for it, are you able to install a custom binary or package with the new version?

**Comment by alexef** [comment] 2017-03-17 07:36
Yes, I am.

**Comment by victorcoder** [comment] 2017-03-27 20:27
@alexef sorry for the delay, could you contact me directly at "victor at victorcastell.com"? and let me know your OS & Architecture. I'll arrange a proper binary. Thanks.

**Comment by victorcoder** [comment] 2018-05-08 11:13
Probably fixed in #344, could you check?

Feel free to reopen

**Closed by victorcoder** 2018-05-08 11:13 UTC
Labels: bug
