### ISSUE TITLE
POST /jobs takes 3 seconds

### ISSUE THREAD

**Issue by redben** [victorcoder/dkron#244] opened 2017-03-14 19:51 UTC
I am trying dkron on my local machine, backed with etcd. I noticed that it takes 3 seconds for the API call to return a response.
Is it normal that jobs take that long to add ? (3 seconds)

**Comment by m1r4ge** [comment] 2017-03-25 18:27
I have the same issue too(

**Comment by victorcoder** [comment] 2017-03-27 14:06
@redben @m1r4ge The process of creating/updating a job takes quite an amount of time because it does checks and validations, and the speed of distributed KV is not it's main sales point :)

Said that, posting a job to Dkron is considered an expensive operation:

- How many of this do you need to do daily?
- How many jobs do you have in your Dkron cluster?

**Comment by m1r4ge** [comment] 2017-03-27 17:40
@victorcoder 
- I don't know how many jobs will be created daily, I create them while handling requests in our web app, so receiving response in 3 seconds is not a very good UX.
- Fresh installation with etcd as a backend storage, there are no jobs at all.

**Comment by victorcoder** [comment] 2017-03-27 20:55
There is a good reason why job creation takes 3s. It should notify the cluster master node with the newly created job.

@m1r4ge @redben I want to understand better your use case.

@m1r4ge are you responding to the end user when dkron ends adding the job?

@redben why you need the creation time to be faster?

**Comment by redben** [comment] 2017-05-19 13:22
Sorry for the delay, I somehow missed the notification...

Here is an example use case :

- There is a service that makes quotes for products that have volatile prices, the quotes have an expiry time. Those quote also put options/lock products in the stock.
- When a quote expires there is some processing. Mainly rolling back stock status...etc

**Option 1** the topic of this issue, kind of "ACID", creating the job is part of the quote creation process, synchronous, but 3 seconds is a lot...

**Option 2** could trigger the job creation asynchronously, out of the transaction... but then should have a third process that checks for discrepancies (quote created but job creation failed)

**Option 3** Have one job that trigger at a very low interval and process all expired quotes.

For now I went with option 3.

**Comment by sysadmind** [comment] 2018-04-12 13:37
I think a lot of the slowness is caused by the valkeyvie library. Dkron uses the `List()` call in that library to get information about jobs or exections from the store. This is a recursive call, and will list not only all values under a key, but also all children of that key. Because not all K/V stores support recursive listing, this is implemented as many recursive calls to list, causing a lot of data transfer and network calls, all of which add time.

I think this is worse on the execution side because of the nested data structure, but I think this contributes a lot to the slowness of dkron in several areas. I hope to add some benchmarking to try and understand where dkron spends its time on calls and add some improvements.

**Comment by houshunwei** [comment] 2018-04-23 03:45
same problem.
Is there a work around for this?

**Comment by victorcoder** [comment] 2018-04-23 22:17
Fixed in #350

**Closed by victorcoder** 2018-04-23 22:17 UTC
