### ISSUE TITLE
0.11.2 Concurrency 'forbid' not always respected

### ISSUE THREAD

**Issue by geoffjukes** [victorcoder/dkron#452] opened 2018-11-06 16:27 UTC
Originally posted to #377

Hi @victorcoder

I'm on 0.11.2 and have noticed that the `concurrency: forbid` is not always respected. I have a very long running process (nearly 2 hours) that I poll every 15 minutes. It is essential that it only one instance is running.

I use Consul as the backend, so thought that might be my issue, but I just completed a migration of the Consul cluster, and the Dkron masters, to greatly reduce the node count, and the latency between the nodes. But dkron seems to erroneously mark an event as complete (erroneously, because I can still see the task is running via `ps aux`) and fires again at the next schedule. If I forcibly kill the event that was marked complete, it gets updated with the new completed timestamp.

I cannot reliably reproduce the issue, as it seems random. Please let me know what I can do to help track down the cause.

Geoff

**Comment by geoffjukes** [comment] 2018-11-06 16:36
Small update, as it just happened, and both instances are running on the same server:
```
    root     20538  0.0  0.0   4628   808 ?        S    07:00   0:00 /bin/sh -c (cd /opt/io/schedule; .env/bin/python event/outgoing.py)
    root     20539  0.0  0.0 167668 33908 ?        Sl   07:00   0:00 .env/bin/python event/outgoing.py
    root     20696  0.0  0.0   4628   880 ?        S    07:15   0:00 /bin/sh -c (cd /opt/io/schedule; .env/bin/python event/outgoing.py)
    root     20697  0.0  0.0 167160 33404 ?        Sl   07:15   0:00 .env/bin/python event/outgoing.py
```
You can see that the first started at 7:00, and the second at 7:15.

The DKRON UI Shows this:

![image](https://user-images.githubusercontent.com/1959570/48078426-4a27ba00-e19e-11e8-86d1-ce2b98aacd42.png)

If I kill the event that started at 7am, the 'Finished at' time changes in DKRON.

![image](https://user-images.githubusercontent.com/1959570/48078554-8b1fce80-e19e-11e8-9724-bf768427df7f.png)

So it appears that something is erroneously marking the first event as complete.

I currently have my logginbg set to 'error' I'll increase it and see what I can glean.

**Comment by victorcoder** [comment] 2018-11-07 10:37
Oh, I responded here https://github.com/victorcoder/dkron/issues/377#issuecomment-436580075 seeing this.

**Comment by geoffjukes** [comment] 2018-11-07 14:28
No worries @victorcoder. I should have created this new ticket first.

The linked code makes sense, as does its purpose (I recall the bug that it fixed)

There is nothing specific that happens at the time of the double run (that I can see). Dkron is obviously finding the job record, as it is setting the timestamp. But the job is still visible via `ps` so it’s not stalled or terminated - and the link back to Dkron is still in-tact, because the timestamp is updated when killed. 

I’ll be in the office in 2 hours, I may be able to find more then.

**Comment by geoffjukes** [comment] 2018-11-10 16:18
Hi @victorcoder

I’m still trying to figure out what’s happening, but I think it might be related to Consul losing/dropping the lock session. 

Right now, 2 instances of the task are running. The record in ‘job_locks’ was held by the first instance. 

I refreshed the Consul KV page, and the lock was gone - But there are still 2 instances running (I have stopped the cron to prevent more running). 


job_executions shows the first instance as completed (it is not) and the second as still active. 

I’m leaning towards this being a Consul issue, but I really don’t know what else to do (I have simplified the Consul cluster, moved the nodes local etc). 

I have no experience with etcd, so I’m nervous about switching.

**Comment by geoffjukes** [comment] 2018-11-10 16:40
An observation:

The Job runs every 15 minutes. 

 "last_error": "2018-11-10T06:20:34.754580324Z",

Job ran again at 06:30 and executed script. 



Then when it ran at 06:45, it should have skipped the script, but it ran it. 

The lock was held by the first instance the whole time.

**Comment by geoffjukes** [comment] 2018-11-10 17:15
One other observation, which is more one borne of confusion - the timestamps seem to be inconsistent. Sometimes they are Timezone-aware, and sometimes they are not, and it’s not always clear if the naïve timestamps are local or UTC. 

For example:
```
"last_success": "2018-11-10T16:30:22.109075605Z",
  "last_error": "2018-11-10T06:20:34.754580324Z"```

The local time here is 09:15, so the ‘last_success’ has to be UTC. But the ‘last_error’ timestamp fits nicely with the issue - but only if it is local time.

**Comment by geoffjukes** [comment] 2018-11-11 03:55
I’m convinced this is an issue with Consul. I upgraded to cluster from 1.2.3 to 1.3.0, and it’s gotten worse. Earlier today, I had 3 instances running across 2 servers. 

I guess I’ll have to bite the bullet and figure out etcd.

**Comment by victorcoder** [comment] 2018-11-12 12:15
@geoffjukes I want to dig into your problem, let me some time to try to reproduce. It should work with consul as with etcd, don't switch yet, let's see what is going on here.

**Comment by victorcoder** [comment] 2018-11-12 15:07
The store locks are not involved in job skipping because of forbid, just omit them in your investigation.

Just for the record, I just did a simple concurrency test and it works as expected. 

As I pointed in the relevant code, when a job is in `forbid`, before launching the job again, dkron asks the nodes that where executing the job if they have finished, every node keeps track of its running jobs (in memory), if they respond that the job has not finished, then the execution is skipped.

I fear that for some reason your running nodes are failing to respond to the request.

Could you set the log-level to debug and send the relevant logs? Specially when the server tries to launch the job again and sends the query to the cluster.

Reach me by email if you need to.

**Comment by geoffjukes** [comment] 2018-11-15 17:30
@victorcoder It's been 3 days, and I've been out sick - which means I haven't been doing any development work (i.e. Deployments) and the Schedule has been running perfectly.

So at this point, I am going to leave Debug enabled and chalk this up to something in my system or code deployments.

Thank you for looking into it. If I start experiencing the issue again, I'll forward any relevant logs.

**Comment by victorcoder** [comment] 2018-11-15 17:32
Thanks @geoffjukes, keep me posted.

**Comment by geoffjukes** [comment] 2018-11-20 17:35
Hi @victorcoder - It's started happening again, but at times when it could not have been a deploy (1am, for example). I have the logs, but I'm not seeing anything useful.

Today at 8am, it executed as expected.
At 8:15, it was still running, and Dkron detected that as expected
At 8:30, it was still running, but DKron did not detect it, marked the old job as complete, and spawned a new instance.

I am attaching the 1am logs, and the 8am logs.
[export_2018-11-20-17-32-31-215.jsonl.gz]
[export_2018-11-20-17-35-03-736.jsonl.gz](https://github.com/victorcoder/dkron/files/2600892/export_2018-11-20-17-35-03-736.jsonl.gz)
(https://github.com/victorcoder/dkron/files/2600886/export_2018-11-20-17-32-31-215.jsonl.gz)

**Comment by geoffjukes** [comment] 2018-11-20 18:42
I'm scanning through all the DKron UI runs:

![image](https://user-images.githubusercontent.com/1959570/48794936-46bd2400-ecb0-11e8-8920-b74d01d74dc6.png)

![image](https://user-images.githubusercontent.com/1959570/48794967-63595c00-ecb0-11e8-85dd-d13ed1616c4a.png)

![image](https://user-images.githubusercontent.com/1959570/48795021-90a60a00-ecb0-11e8-8014-9bafd4ed3128.png)

It looks like manager-01-p is always involved - but manager-01-p is also the master, so that might be a red herring.

It's worrying that the top screenshot clearly shows the job running twice on manager-01-p - like it couldn't even check itself.

What does dkron store in-memory about the runs? and what can cause it to forget? I'm certainly not restarting dkron at these times.

**Comment by victorcoder** [comment] 2018-11-20 21:59
It uses a globally defined `sync.Map` to store what's running https://github.com/victorcoder/dkron/blob/master/dkron/invoke.go#L49

I've been looking at the logs but I don't see anything relevant.

What I am suspecting is that the execution done query is not obtaining the expected results.

I think this will need a refactor based on GPRC calls, I will try to come with a solution.

**Comment by geoffjukes** [comment] 2018-11-20 22:08
If I can help debug/test anything @victorcoder, please let me know.

I personally never had the orphan issue. But maybe, rather than checking it on every run attempt, add a setting like "max_misses" or something, which would allow up 'x' missed runs before checking for orphans. Default value of 0 would keep current behavior unchanged.

Then I could just set mine to a number suitably high (I know exactly how many missed runs are acceptable for my script).

**Comment by victorcoder** [comment] 2018-11-20 22:37
Checking again the logs, I can see what's going on: `08:30:00 [WARN] serf: query reply ID mismatch (Local: 544050389, Response: 508792713)`

I don't know what is it but doesn't looks good, the response is not being delivered correctly for some reason.

**Comment by geoffjukes** [comment] 2018-11-20 22:45
@victorcoder Based on the timings, these often correlate to the second run (the one that should not run), although it's not a 1-for-1.

[export_2018-11-20-22-41-11-957.jsonl.gz](https://github.com/victorcoder/dkron/files/2601862/export_2018-11-20-22-41-11-957.jsonl.gz)

**Comment by victorcoder** [comment] 2018-11-20 22:50
ok, and another weird thing is this line `agent: Execution is not running\" group= node=manager-01-p`

`group` is empty when the agent receives an execution done query. This indicates that there is no problem at all with the execution done query but with the runningExecutions map.

**Comment by victorcoder** [comment] 2018-12-02 21:39
Fixed in https://github.com/victorcoder/dkron/commit/53d8464f4b3aae7715fdc755233d99b5f8658b33

**Closed by victorcoder** 2018-12-02 21:39 UTC
Labels: bug
