### ISSUE TITLE
Plugins not cleaned up on Fatal config load

### ISSUE THREAD

**Issue by sysadmind** [victorcoder/dkron#332] opened 2018-02-13 15:39 UTC
While testing dkron, I left the improper example config (via config/dkron.json) `"encrypt": "a-valid-key-generated-with-dkron-keygen",`. This results in a Fatal error as expected, however the plugins have been started by this point and after the Fatal error, the plugin processes are not reaped, leading to them running forever until manually cleaned up. I was able to run the agent process several times and observe a cumulative set of plugin processes running for each run of the agent.

Example output of running `dkron.exe agent`:
```
Invalid encryption key: illegal base64 data at input byte 1
FATA[2018-02-13T10:35:41-05:00] agent: Can not setup serf
```

Environment:
```
dkron.exe version
Dkron v0.9.6
Agent Protocol: 5 (Understands back to: 2)
```
OS: Windows Server 2016

**Comment by victorcoder** [comment] 2018-05-10 21:18
Duplicate of #247

**Closed by victorcoder** 2018-05-10 21:18 UTC
