### ISSUE TITLE
Dkron missed multiple executions

### ISSUE THREAD

**Issue by mrutunjayachavadi** [victorcoder/dkron#346] opened 2018-04-12 07:44 UTC
We are running dkron with etcd, both single instance
Dkron Version : dkron_0.9.6_linux_amd64
etcd version : etcd-v3.3.0-linux-amd64

We missed couple of executions for multiple schedules
ex : a job scheduled to run at 18:00 IST for all days of week
I had scheduled jobs from 17:59 to 18:11 each minute, only the schedule at 17:59 got executed and all others are missed.

Also we missed schedules at 1,2,3,4,5 am IST for multiple days, but schedules at 1.30,2.30 till 7.30 am got executed.

Job Schedule JSON at 18:00 IST:

{
	"name": "5a8e9328fcba75001500004a-8cb77472-310f-46c2-970e-9c2666cf5456",
	"schedule": "20 0 18 29 * *",
	"shell": true,
	"command": "echo 5a8e9328fcba75001500004a-8cb77472-310f-46c2-970e-9c2666cf5456",
	"environment_variables": null,
	"owner": "abc@xyz.com",
	"owner_email": "bc@xyz.com",
	"success_count": 0,
	"error_count": 0,
	"last_success": "0001-01-01T00:00:00Z",
	"last_error": "0001-01-01T00:00:00Z",
	"disabled": false,
	"tags": null,
	"retries": 3,
	"dependent_jobs": null,
	"parent_job": "",
	"processors": null,
	"concurrency": "allow"
}

Sometimes we also see the below error:
time="2018-04-12T12:03:14+05:30" level=error msg="Key not found in store" node=btc5x324

PLease suggest us, what to do next, we are not able to debug the issue.

[dkron_logs.txt](https://github.com/victorcoder/dkron/files/1901805/dkron_logs.txt)

**Comment by victorcoder** [comment] 2018-04-12 08:15
Hi @mrutunjayachavadi I can't really dig into the problem, could you paste the cron expression and the intended schedule in words that you need to do?

For example: "20 0 18 29 * *" This means 18:00:20 UTC on day 29th every month every year

I recommend that you take a look to the cron spec in the docs https://dkron.io/usage/guides/#cron-expression-format

**Comment by mrutunjayachavadi** [comment] 2018-04-12 10:51
Cron expression format ::0 0 15 * * 0,1,2,3,4,5,6
The intended schedule is, it should run everyday at 3 pm(15:00)

**Comment by victorcoder** [comment] 2018-04-12 12:11
`0 0 1 * * 0,1,2,3,4,5,6`: why don't use `0-6` or simply `*`

It should work anyway

**Comment by mrutunjayachavadi** [comment] 2018-04-12 12:27
Hi Victor

I tried with 0-6, but no luck.
Not only the issue is with all days even for one days ex0 0 1 * * 4
Run a job 1 am everday..Looks like these jobs are also missing.
Could not find any pattern for which jobs are missing, but all other jobs scheduled at 1.30 am 
2.30 am 3.30 am....so on

Is there a problem with etcd running as only one instance?

**Comment by victorcoder** [comment] 2018-04-14 22:31
There should be no problem running a single instance of etcd. This is very strange, do you mean that it only miss executions when scheduled at 1:00?

**Comment by mrutunjayachavadi** [comment] 2018-04-16 07:51
Hi victor,

Not only schedule at 1:00, but all below schedules are missing some days and able to get these for other days.

Daily schedule at 1:00 am
Daily schedule at 1:00 am
Daily schedule at 1:00 am
Daily schedule at 1:00 am
Daily schedule at 1:00 am

**Comment by victorcoder** [comment] 2018-11-27 21:05
Closing this because I'm unable to reproduce it and lack of more info. Try with the latest version and feel free to reopen if you experience the issue again.

**Closed by victorcoder** 2018-11-27 21:05 UTC
Labels: invalid
