### ISSUE TITLE
Dasboard crash

### ISSUE THREAD

**Issue by whizz** [victorcoder/dkron#80] opened 2016-02-25 08:28 UTC
After a while of running, with no immediately apparent reason, the dashboard starts crashing on any request with following log:

```
2016-02-25_08:08:29.59255 2016/02/25 09:08:29 http: panic serving 10.9.233.79:64571: runtime error: invalid memory address or nil pointer dereference
2016-02-25_08:08:29.59256 goroutine 24472 [running]:
2016-02-25_08:08:29.59256 net/http.(*conn).serve.func1(0xc820222160, 0x7faffff49240, 0xc820118010)
2016-02-25_08:08:29.59257       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5
2016-02-25_08:08:29.59257 github.com/victorcoder/dkron/dkron.newCommonDashboardData(0xc82010e820, 0xc820162280, 0x16, 0x0, 0x0, 0x0)
2016-02-25_08:08:29.59257       /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:33 +0x55f
2016-02-25_08:08:29.59258 github.com/victorcoder/dkron/dkron.(*AgentCommand).dashboardIndexHandler(0xc82010e820, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59258       /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:73 +0x4a7
2016-02-25_08:08:29.59258 github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.dashboardIndexHandler)-fm(0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59258       /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:43 +0x3e
2016-02-25_08:08:29.59259 net/http.HandlerFunc.ServeHTTP(0xc820229bb0, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59259       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
2016-02-25_08:08:29.59261 github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82010eaf0, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59261       /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
2016-02-25_08:08:29.59261 github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59262       /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
2016-02-25_08:08:29.59262 net/http.HandlerFunc.ServeHTTP(0xc820174f90, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59262       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
2016-02-25_08:08:29.59262 github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59263       /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:75 +0x1ac
2016-02-25_08:08:29.59263 net/http.HandlerFunc.ServeHTTP(0xc820175080, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59264       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
2016-02-25_08:08:29.59264 github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc8202365e0, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59264       /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:85 +0x6c
2016-02-25_08:08:29.59264 net/http.serverHandler.ServeHTTP(0xc820137c20, 0x7faffff495b0, 0xc8201c4160, 0xc8200da2a0)
2016-02-25_08:08:29.59265       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1862 +0x19e
2016-02-25_08:08:29.59265 net/http.(*conn).serve(0xc820222160)
2016-02-25_08:08:29.59265       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1361 +0xbee
2016-02-25_08:08:29.59265 created by net/http.(*Server).Serve
2016-02-25_08:08:29.59267       /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1910 +0x3f6
```

**Comment by victorcoder** [comment] 2016-02-28 22:56
In this state, could you please post the output of `/v1/members` and `/v1`?

**Comment by mlafeldt** [comment] 2016-03-21 15:04
We actually experienced the same issue while doing resilience testing. After intentionally terminating two out of three etcd instances, the following stack trace appeared in our logs:

```
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  time="2016-03-15T12:43:15Z" level=error msg="client: etcd cluster is unavailable or misconfigured"
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  2016/03/15 12:43:15 http: panic serving 10.8.1.76:17437: runtime error: invalid memory address or nil pointer dereference
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  goroutine 40 [running]:
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.(*conn).serve.func1(0xc82015c2c0, 0x7fad0ef04738, 0xc820144038)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.(*AgentCommand).leaderMember(0xc82000b1d0, 0x13, 0x0, 0x0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:509 +0x5c
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.newCommonDashboardData(0xc82000b1d0, 0xc8200fb560, 0x27, 0x0, 0x0, 0x0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:30 +0x33
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.(*AgentCommand).dashboardIndexHandler(0xc82000b1d0, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:71 +0x4a7
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.dashboardIndexHandler)-fm(0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:43 +0x3e
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.HandlerFunc.ServeHTTP(0xc8201f5980, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000bd10, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.HandlerFunc.ServeHTTP(0xc820143800, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:77 +0x1ac
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.HandlerFunc.ServeHTTP(0xc820143830, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc8201c5f00, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:85 +0x6c
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.serverHandler.ServeHTTP(0xc8201fc960, 0x7fad0eebe7d8, 0xc82015c370, 0xc8201ce0e0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1862 +0x19e
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.(*conn).serve(0xc82015c2c0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1361 +0xbee
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  created by net/http.(*Server).Serve
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1910 +0x3f6
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  time="2016-03-15T12:43:15Z" level=error msg="client: etcd cluster is unavailable or misconfigured"
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  time="2016-03-15T12:43:15Z" level=info msg="agent: Successfully set leader" key=28cb2541dfca8be01e91140b57ddd89475ca7730
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  time="2016-03-15T12:43:15Z" level=debug msg="agent: Restarting scheduler"
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  time="2016-03-15T12:43:15Z" level=error msg="client: etcd cluster is unavailable or misconfigured"
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  2016/03/15 12:43:15 http: panic serving 10.8.2.126:45005: runtime error: invalid memory address or nil pointer dereference
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  goroutine 50 [running]:
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.(*conn).serve.func1(0xc8202182c0, 0x7fad0ef04738, 0xc8200202c0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.(*AgentCommand).leaderMember(0xc82000b1d0, 0x13, 0x0, 0x0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:509 +0x5c
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.newCommonDashboardData(0xc82000b1d0, 0xc8200fb560, 0x27, 0x0, 0x0, 0x0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:30 +0x33
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.(*AgentCommand).dashboardIndexHandler(0xc82000b1d0, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:71 +0x4a7
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.dashboardIndexHandler)-fm(0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:43 +0x3e
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.HandlerFunc.ServeHTTP(0xc8201f5980, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000bd10, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.HandlerFunc.ServeHTTP(0xc82021e540, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:77 +0x1ac
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.HandlerFunc.ServeHTTP(0xc82021e570, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc8201c5f00, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:85 +0x6c
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.serverHandler.ServeHTTP(0xc8201fc960, 0x7fad0eebe7d8, 0xc820218370, 0xc8200d6fc0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1862 +0x19e
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  net/http.(*conn).serve(0xc8202182c0)
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1361 +0xbee
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  created by net/http.(*Server).Serve
Mar 15 13:43:15 ip-10-8-3-27.eu-west-1.compute.internal dkron:  /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1910 +0x3f6
Mar 15 13:43:21 ip-10-8-3-27.eu-west-1.compute.internal dkron:  time="2016-03-15T12:43:21Z" level=fatal msg="client: etcd cluster is unavailable or misconfigured"
```

We're currently running dkron v0.6.4.

The panic happens here https://github.com/victorcoder/dkron/blob/v0.6.4/dkron/agent.go#L509 where the return value of `GetLeader` isn't checked.

Moreover, the dashboard code calling the above code doesn't check the error either: https://github.com/victorcoder/dkron/blob/v0.6.4/dkron/dashboard.go#L30

At least the first problem seems to be fixed (by coincidence?) in master by https://github.com/victorcoder/dkron/commit/6be999e1f6bac26ea3cc5c20a7f8be6067e999bc

The dashboard still crashes in case there's no leader. Something like this would make the code more robust:

```diff
diff --git a/dkron/dashboard.go b/dkron/dashboard.go
index ae4b400..6a47620 100644
--- a/dkron/dashboard.go
+++ b/dkron/dashboard.go
@@ -27,10 +27,13 @@ type commonDashboardData struct {
 }

 func newCommonDashboardData(a *AgentCommand, nodeName, path string) *commonDashboardData {
-       l, _ := a.leaderMember()
+       leaderName := "n/a"
+       if l, err := a.leaderMember(); err != nil {
+               leaderName = l.Name
+       }
        return &commonDashboardData{
                Version:    a.Version,
-               LeaderName: l.Name,
+               LeaderName: leaderName,
                MemberName: nodeName,
                Backend:    a.config.Backend,
                Path:       fmt.Sprintf("%s%s", path, dashboardPathPrefix),
```

However, I'm not sure if this fixes all problems. I suggest to test the code and make sure that it gracefully handles the situation where there's no leader elected, e.g. by printing an error message.

/cc @Luzifer @seiffert

**Comment by mlafeldt** [comment] 2016-03-29 14:52
@victorcoder What do you think?

**Comment by victorcoder** [comment] 2016-04-04 20:23
@mlafeldt Exactly, all this errors won't happen with the new leader election system to be released in 0.7 that I'm going to roll today or tomorrow.

Closing this in the meantime, and I'll reopen or reference if something similar occurs with the new version.

**Comment by mlafeldt** [comment] 2016-04-06 10:03
@victorcoder Even with the new leader election, `leaderMember` might still return `nil` (https://github.com/victorcoder/dkron/blob/master/dkron/agent.go#L521-L529), which in turn will still crash here: https://github.com/victorcoder/dkron/blob/master/dkron/dashboard.go#L30

I strongly suggest to reopen this issue.

**Comment by Luzifer** [comment] 2016-04-14 15:40
Issue is still present in 0.7.0:

```
Apr 14 15:27:21 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: time="2016-04-14T15:27:21Z" level=info msg="agent: Listen for events" node=ip-10-8-4-245.eu-west-1.compute.internal
Apr 14 15:27:21 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: time="2016-04-14T15:27:21Z" level=info msg="agent: Cluster leadership lost" node=ip-10-8-4-245.eu-west-1.compute.internal
Apr 14 15:29:00 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: 2016/04/14 15:29:00 http: panic serving 10.8.2.31:42724: runtime error: invalid memory address or nil pointer dereference
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: goroutine 66 [running]:
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: net/http.(*conn).serve.func1(0xc820108d10, 0x7f48432bc6e8, 0xc820022000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/dkron.newCommonDashboardData(0xc820014360, 0xc8201015f0, 0x28, 0x0, 0x0, 0x0)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:33 +0x55f
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/dkron.(*AgentCommand).dashboardIndexHandler(0xc820014360, 0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:71 +0x4a7
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.dashboardIndexHandler)-fm(0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/dashboard.go:43 +0x3e
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: net/http.HandlerFunc.ServeHTTP(0xc82020e5a0, 0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000de00, 0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: net/http.HandlerFunc.ServeHTTP(0xc8202ceed0, 0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:78 +0x1ac
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: net/http.HandlerFunc.ServeHTTP(0xc8202cef00, 0x7f4843278068, 0xc82018bb80, 0xc820256000)
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
Apr 14 15:29:01 ip-10-8-4-245.eu-west-1.compute.internal dkron[989]: github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc8201d7d20, 0x7f4843278068, 0xc82018bb80, 0xc820256000)
[…]
```

Please reopen this issue and fix the underlying problem (nil-pointer dereference).

**Comment by victorcoder** [comment] 2016-04-14 21:27
This would be a trivial fix, but I want to know the real underlaying problem. In theory there can't be a leader value that doesn't belongs to the serf cluster, **unless** the member just failed and the key TTL is still active.

That moment is the only moment that stored leader value won't be part of the serf cluster, and even in this case the member will be in `failed` status and there are no status check in https://github.com/victorcoder/dkron/blob/master/dkron/agent.go#L523

The other option is at the start, a request from the dashboard comes in and there's still no leader elected.

I've never experienced this error and before applying the fix I would like to know if you can identify one of those cases.

**Comment by Luzifer** [comment] 2016-04-14 23:16
The example I observed is this one:

- Some agent (`no1`) writes itself to the `leader` key and then gets terminated by the auto-scaling group
- Another agent (`no2`) starts in the auto-scaling group, never saw `no1` and gets a request to `/dashboard`. In this case it tries to load information about `no1` which it can't load and then tries to do a `nil.Name`. Afterwards it dies and the process starts again as the auto-scaling group is starting more and more machines.

This fixes itself in the moment there is no machine left and the key gets removed. Afterwards the first machine will be the leader, the second machine joins the cluster and both are happy.

In general the case is reproducible quite easy: Fill the `leader` key with something random, let a new agent start and query its dashboard. While trying to display information about the leader it will die with a huge stack trace.

What I'm expecting in this case is that this response (`nil`) is handled gracefully. Maybe just the answer "oops didn't get information about the leader" instead of a panic… If I understand the timeout correctly the client then should be able to get into a new leader election it it does not die before…

**Comment by victorcoder** [comment] 2016-04-22 16:07
thanks @Luzifer, seems legit. Just look at the PR

**Closed** 2016-04-22 16:07 UTC
Labels: bug
