### ISSUE TITLE
Why load all record in pagination

### ISSUE THREAD

**Issue by pMonfared** [victorcoder/dkron#548] opened 2019-06-17 14:08 UTC
Pagination doesn't work correctly in dashboard, why load all record ? get 10 record per page
please fix that!

![image](https://user-images.githubusercontent.com/10448255/59610561-e5b6db00-912e-11e9-98db-d73ffb597830.png)

**Comment by victorcoder** [comment] 2019-06-17 15:03
@pMonfared What is not working for you?

**Comment by victorcoder** [comment] 2019-06-17 15:05
Needs to use the issue reporting template.

**Comment by pMonfared** [comment] 2019-06-17 21:31
pagination :
load 10 record per page, not load all records with one request!
if you get all record with one request , why use pagination?
and i search a title when current page is 1 , don't show filtered record, show nothing but filtered record found on other page!

**Comment by victorcoder** [comment] 2019-06-21 15:13
> if you get all record with one request , why use pagination?

Modern browsers are perfectly capable of rendering thousands of json objects without problems. The question is, why you shouldn't use pagination? It's unreadable to show thousands of records in the same page. This is why solutions like pagination.js exists.

> and i search a title when current page is 1 , don't show filtered record,

That's right the filter is per page, not the whole set.

**Comment by fopina** [comment] 2019-06-25 14:45
@victorcoder regardless of the way this was reported, do you consider filtering being per page a bug or was it intended? just wondering as it was something I had planned to do a PR if it's not changed in v2

**Comment by saeedmsdi** [comment] 2019-06-30 11:11
@victorcoder pagination required on large records. modern browsers cant support 1milion records! and loading this huge records is unuseful. 

and for the filtering : like I need today schedules failed, or next day scheduled. it's very useful for us to find filtered records

thanks

**Comment by victorcoder** [comment] 2019-06-30 21:32
@fopina filtering per page was intended but doesn't mean it's ideal, the impossibility to dedicate more time it was the most decent solution at the time.

I gladly accept a PR addressing this issues, though I will try to work on it too.

**Comment by victorcoder** [comment] 2019-07-01 21:32
We are mixing several issues here, let's close this as fixed in #561 and reopen a feature request or PR for filtering.

**Closed by victorcoder** 2019-07-01 21:32 UTC
